// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfbKhL8NpdqXVqErxhZB-JzvrC8ZjISrU',
    appId: '1:31944077951:web:375448d00a981d0fe2c54a',
    messagingSenderId: '31944077951',
    projectId: 'tedikap-app',
    authDomain: 'tedikap-app.firebaseapp.com',
    storageBucket: 'tedikap-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3X5yj2s3rdBze820AwKWUOl2P3zhPTqE',
    appId: '1:31944077951:android:69de4f6d609d1842e2c54a',
    messagingSenderId: '31944077951',
    projectId: 'tedikap-app',
    storageBucket: 'tedikap-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEJWiYdcN5r9F15shGwNWjkJ71RF2l0ic',
    appId: '1:31944077951:ios:ea89b0443364434be2c54a',
    messagingSenderId: '31944077951',
    projectId: 'tedikap-app',
    storageBucket: 'tedikap-app.appspot.com',
    iosBundleId: 'com.example.tedikapFlutterApp',
  );
}
